name: shrine
description: Learn how to use Material for structure and layout.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0-nullsafety.2

  cupertino_icons: ^1.0.3
  shrine_images: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  # TODO: Insert Fonts (103)
  uses-material-design: true
  assets:
    - assets/
